# https://github.com/marketplace/actions/helm-chart-releaser
name: Release Charts

on:
  push:
    # Change this to the branches you want to trigger a new Helm chart release
    branches:
      - main
  # Allow running manual via the GitHub Actions Web UI:
  workflow_dispatch:

jobs:
  release:
    # depending on default permission settings for your org (contents being read-only or read-write for workloads), you will have to add permissions
    # see: https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_token
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Build dependencies
        run: |
          helm repo add dandydev https://dandydeveloper.github.io/charts
          cd charts/helm-charts-post && helm dependency build

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
